create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('projetosComIa', 'projetosSemIa', 'certificados')),
  title text not null,
  description text not null default '',
  technologies text not null default '',
  image_url text,
  image_data text,
  site_url text,
  github_url text,
  sort_order integer not null default 0,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint portfolio_items_image_source check (image_url is not null or image_data is not null or (image_url is null and image_data is null))
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

grant select on public.portfolio_items to anon, authenticated;
grant select on public.admin_users to authenticated;
grant insert, update, delete on public.portfolio_items to authenticated;
grant usage, select on sequence public.portfolio_items_id_seq to authenticated;

alter table public.admin_users enable row level security;
alter table public.portfolio_items enable row level security;

drop policy if exists "Admins can see their own authorization" on public.admin_users;
create policy "Admins can see their own authorization"
  on public.admin_users for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "Anyone can read portfolio items" on public.portfolio_items;
create policy "Anyone can read portfolio items"
  on public.portfolio_items for select to anon, authenticated
  using (true);

drop policy if exists "Admins can add portfolio items" on public.portfolio_items;
create policy "Admins can add portfolio items"
  on public.portfolio_items for insert to authenticated
  with check (public.is_admin() and created_by = (select auth.uid()));

drop policy if exists "Admins can edit portfolio items" on public.portfolio_items;
create policy "Admins can edit portfolio items"
  on public.portfolio_items for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete portfolio items" on public.portfolio_items;
create policy "Admins can delete portfolio items"
  on public.portfolio_items for delete to authenticated
  using (public.is_admin());

create or replace function public.set_portfolio_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists portfolio_items_updated_at on public.portfolio_items;
create trigger portfolio_items_updated_at
  before update on public.portfolio_items
  for each row execute function public.set_portfolio_updated_at();

-- Depois de criar um usuário em Authentication > Users, autorize-o com:
-- insert into public.admin_users (user_id, email)
-- select id, email from auth.users where email = 'seu-email@exemplo.com';
